module.exports = {
  rules: {
    quotes: [2, 'single', {avoidEscape: true}],
    'operator-linebreak': 0,
    'implicit-arrow-linebreak': 0,
    'no-implicit-globals': 2,
    'no-restricted-globals': 2,
    'object-curly-spacing': ['error', 'never'],
    'object-curly-newline': 0,
    'function-paren-newline': 0,
    'arrow-parens': 0,
    'import/no-unresolved': 0,
    'import/no-extraneous-dependencies': 0,
    'no-console': 0,
    'no-underscore-dangle': 0,
    'no-unused-vars': ['error', {argsIgnorePattern: 'next'}],
    'no-use-before-define': ['error', {variables: false}],
    'no-multi-str': 0,
  },
};
